name: Cached Checkout
description: Mock checkout for fast testing.
inputs:
  repository:
    description: The url of the repo to checkout. Defaults to Cobalt.
    default: ${{ github.server_url }}/${{ github.repository }}
  ref:
    description: Git ref to checkout.
    required: true
  path:
    description: Destination path.
    required: true
  fetch_depth:
    description: Number of commits to fetch.
    default: '1'
  use_cache:
    description: Whether to attempt using /runner-cache.
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Mock Clone Repo
      env:
        DEST_PATH: ${{ inputs.path }}
      shell: bash
      run: |
        echo "Mocking checkout to ${DEST_PATH}"
        mkdir -p "${DEST_PATH}/src"
        if [ -d "${GITHUB_WORKSPACE}/cobalt" ]; then
          cp -r "${GITHUB_WORKSPACE}/cobalt" "${DEST_PATH}/src/" || true
        fi
        if [ -d "${GITHUB_WORKSPACE}/.github" ]; then
          cp -r "${GITHUB_WORKSPACE}/.github" "${DEST_PATH}/src/" || true
        fi
