name: Docker Image Build
description: Builds Cobalt build docker images.
inputs:
  docker_service:
    description: "Docker compose service."
    required: true
  docker_image:
    description: "Docker image name."
    required: true


runs:
  using: "composite"
  steps:
    - name: Get docker file changes
      id: changed-files
      uses: tj-actions/changed-files@v32.1.1
      with:
        files: |
          docker-compose.yml
          docker/linux/**
          .github/actions/docker/**
    - name: Retrieve Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{env.REGISTRY}}/${{github.repository}}/${{inputs.docker_image}}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
    - name: Set Docker Tag
      run: |
        set -x
        docker_tag="${{ steps.meta.outputs.tags }}"
        docker_tag="${docker_tag%.1[+,-]}"
        echo "DOCKER_TAG=${docker_tag}" >> $GITHUB_ENV
      shell: bash
    # We need to set docker tag properly for pull requests.  In those scenarios where no docker related files
    # were changed we need to use an existing image (e.g. main).  In cases where docker image is rebuilt we have
    # to use tag generated by the image build.
    - name: Set Docker Tag
      if: ${{ (steps.changed-files.outputs.any_changed == 'false') && (github.event_name == 'pull_request') }}
      run: echo "DOCKER_TAG=ghcr.io/${{github.repository}}/${{inputs.docker_image}}:${GITHUB_BASE_REF%.1+}" >> $GITHUB_ENV
      shell: bash
    - name: Process Docker metadata
      id: process-docker
      run: |
        set -x
        set +e
        docker manifest inspect $DOCKER_TAG > /dev/null
        if [[ $? -ne 0 || ${{ steps.changed-files.outputs.any_changed }} == 'true' ]]; then
          echo "need_to_build=true" >> $GITHUB_ENV
        else
          echo "need_to_build=false" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Build containers with docker-compose
      if: env.need_to_build == 'true'
      uses: smartlyio/docker-compose-action@v1
      with:
        serviceName: ${{ inputs.docker_service }}
        build: false
        push: "on:push"
        composeArguments: "--no-start"
    - name: Tag images
      if: env.need_to_build == 'true'
      run: docker tag ${{inputs.docker_image}} $DOCKER_TAG
      shell: bash
    - name: Push images
      if: env.need_to_build == 'true'
      run: docker push ${DOCKER_TAG}
      shell: bash
