name: On Host Tests
description: Runs on-host tests.
inputs:
  nightly:
    description: "Indicates if this is a nightly job."
    required: true
  test_artifacts_key:
    description: "Artifact key used to store test artifacts."
    required: true
  test_results_key:
    description: "Artifact key used to store test results."
    required: true
  num_gtest_shards:
    description: "Total number of shards used to run the steps in this file."
    required: true
  test_executables_json:
    description: "JSON array of test executables to run."
    required: true
  test_type:
    description: "The test type (gtest or junit)."
    required: false
    default: "gtest"
runs:
  using: "composite"
  steps:
    - name: Set Up Depot Tools
      uses: ./.github/actions/depot_tools
      with:
        run_sync: 'false'
    - name: Checkout JUnit Dependencies
      if: inputs.test_type == 'junit'
      shell: bash
      run: |
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        git sparse-checkout add --skip-checks testing build third_party/catapult third_party/logdog
        git submodule update --init third_party/catapult
    - name: Download Artifacts
      uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
      with:
        name: ${{ inputs.test_artifacts_key }}
    - name: Extract Artifacts
      shell: bash
      run: |
        set -x
        tar -I 'zstd -T0' -xf test_artifacts.tar.zstd
    - name: Prepare Test Execution
      id: prepare-test-execution
      shell: bash
      env:
        PLATFORM: ${{ matrix.platform }}
        CONFIG: ${{ matrix.config }}
        SHARD: ${{ matrix.shard }}
      run: |
        set -x
        env

        out_dir="${GITHUB_WORKSPACE}/out/${PLATFORM}_${CONFIG}"
        # TODO: LD_LIBRARY_PATH should not include the starboard subdirectory.
        LD_LIBRARY_PATH="${out_dir}/starboard:${out_dir}"
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}" >> "${GITHUB_ENV}"

        # TODO: b/467135717 - Remove this once tests don't have asan leaks.
        # Don't fail if only asan fails.
        echo "ASAN_OPTIONS=exitcode=0" >> "${GITHUB_ENV}"

        # Make results dir available to the archiving step below.
        results_dir="${GITHUB_WORKSPACE}/results"
        echo "results_dir=${results_dir}" >> "${GITHUB_ENV}"

        # Test results (xml and logs) must be in a subfolder in results_dir
        # to be picked up by the test result processor.
        # This also prevents accidental overwriting when collecting results.
        test_output="${results_dir}/shard_${SHARD}"
        mkdir -p "${test_output}"
        echo "test_output=${test_output}" >> "${GITHUB_ENV}"

    - name: Run Mocked Tests
      shell: bash
      env:
        JOB_NAME: ${{ matrix.name }}_on_host_tests_${{ matrix.shard }}
        TEST_EXECUTABLES_JSON: ${{ inputs.test_executables_json }}
      run: |
        python3 "${GITHUB_WORKSPACE}/.github/scripts/mock_step.py" \
          --job-name "${JOB_NAME}" \
          --job-type test \
          --output-dir "${test_output}" \
          --test-targets "${TEST_EXECUTABLES_JSON}"
    - name: Archive Test Results
      if: success() || failure()
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: ${{ inputs.test_results_key }}
        path: ${{ env.results_dir }}/*
