name: Internal Tests
description: Runs internal tests (Mocked).
inputs:
  test_dimensions:
    description: "Test dimensions JSON string."
    default: "{}"
  test_targets:
    description: "Test targets."
    required: true
  test_type:
    description: "Test type (e.g. e2e_test or yts_test)"
    required: true
  artifact_name:
    description: "The name of the artifact to be used for tests (e.g., Cobalt.apk)."
    default: "Cobalt.apk"
  test_device_family:
    description: "The test device family (e.g., rdk)."
    default: ""

runs:
  using: "composite"
  steps:
    - name: Run Internal Tests (Mocked)
      shell: bash
      env:
        JOB_NAME: ${{ matrix.name }}_${{ inputs.test_type }}s
      run: |
        python3 "${GITHUB_WORKSPACE}/.github/scripts/mock_step.py" \
          --job-name "${JOB_NAME}" \
          --job-type test \
          --output-dir "${GITHUB_WORKSPACE}/results" \
          --test-targets '${{ inputs.test_targets }}'
