name: Test Artifact Upload
description: Uploads test archives for on-device and on-host tests.
inputs:
  upload_e2e_test_artifacts:
    description: "Indicates if E2E test artifacts should be uploaded."
    required: true
  upload_on_host_test_artifacts:
    description: "Indicates if on-host test artifacts should be uploaded."
    required: true
  upload_on_device_test_artifacts:
    description: "Indicates if on-device test artifacts should be uploaded."
    required: true
  test_artifacts_key:
    description: "Artifact key used to store on-host test artifacts."
    required: true
  test_targets_json_file:
    description: "The path to test targets json file."
    required: true
  platform:
    description: "The platform for which artifacts are being uploaded."
    required: true
  config:
    description: "The build configuration (e.g., devel, qa, gold)."
    required: true
runs:
  using: "composite"
  steps:
    - name: Create Dummy Archives (Mocked)
      shell: bash
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
        touch dummy.txt
        tar --zstd -cf "${GITHUB_WORKSPACE}/artifacts/test_artifacts.tar.zstd" dummy.txt
        tar --zstd -cf "${GITHUB_WORKSPACE}/artifacts/cobalt_browsertests_deps.tar.zstd" dummy.txt
    - name: Upload On-Host Test Artifacts Archive
      if: inputs.upload_on_host_test_artifacts == 'true'
      uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
      with:
        name: ${{ inputs.test_artifacts_key }}
        path: artifacts/*
        retention-days: 3
    - name: Upload On-Device Test Artifacts to GCS (Disabled in Sandbox)
      if: (inputs.upload_on_device_test_artifacts == 'true' || inputs.upload_e2e_test_artifacts == 'true') && false
      env:
        WORKFLOW: ${{ github.workflow }}
        PLATFORM: ${{ inputs.platform }}
        CONFIG: ${{ inputs.config }}
        UPLOAD_E2E_TEST_ARTIFACTS: ${{ inputs.upload_e2e_test_artifacts }}
      run: |
        set -eux
        project_name=$(gcloud config get-value project)

        # Add Cobalt release artifacts for smoke tests.
        if [[ "${UPLOAD_E2E_TEST_ARTIFACTS}" == "true" ]]; then
          mv ${GITHUB_WORKSPACE}/cobalt/src/out/test-package/* \
             ${GITHUB_WORKSPACE}/artifacts/
        fi

        # Upload cobalt.apk for smoke tests.
        if [[ "${PLATFORM}" == *android* ]]; then
          cp "${GITHUB_WORKSPACE}/cobalt/src/out/${PLATFORM}_${CONFIG}/apks/Cobalt.apk" \
             "${GITHUB_WORKSPACE}/artifacts/"
        fi

        gcloud storage cp -r "${GITHUB_WORKSPACE}/artifacts/*" \
          "gs://${project_name}-test-artifacts/${WORKFLOW}/${GITHUB_RUN_NUMBER}/${PLATFORM}/"
      shell: bash
