name: Test Artifact Upload
description: Uploads test archives to GCS and runs on-device tests.
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.6.2
    - name: Configure Environment
      run: |
        set -x
        project_name=$(gcloud config get-value project)
        PLATFORM=${{matrix.platform}}
        echo "PLATFORM=${{matrix.platform}}" >> $GITHUB_ENV
        echo "ARCHIVE_FILE=${PLATFORM}_${{matrix.config}}.tar.xz" >> $GITHUB_ENV
        echo "ARCHIVE_PATH=$GITHUB_WORKSPACE/${PLATFORM}_${{matrix.config}}.tar.xz" >> $GITHUB_ENV
        echo "DESTINATION=${project_name}-test-artifacts/${{github.workflow}}/${GITHUB_RUN_NUMBER}/${{matrix.platform}}_${{matrix.config}}/" >> $GITHUB_ENV
        echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        project_name=$(gcloud config get-value project)
      shell: bash
    - name: Create Test Files Archive
      run: |
        set -x
        [ -f "${ARCHIVE_PATH}" ] && rm -rf "${ARCHIVE_PATH}"
        python3 $GITHUB_WORKSPACE/tools/create_archive.py --intermediate -d ${{env.ARCHIVE_FILE}} -s $GITHUB_WORKSPACE/out/${PLATFORM}_${{matrix.config}} --parallel
      shell: bash
    - name: Copy Test Files to GCS
      id: upload-test-archive
      shell: bash
      run: |
        set -eux
        gsutil -d cp "${ARCHIVE_PATH}" "gs://${DESTINATION}"
