name: android

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  mock-android:
    runs-on: ubuntu-latest
    steps:
      - name: Create mock reports
        run: |
          for platform in chromium_android-arm64 chromium_android-arm chromium_android-x86 android-arm64 android-arm android-x86; do
            jq -n \
              --arg platform "$platform" \
              '{
                platform: $platform,
                config: "devel",
                build_result: "success",
                on_device_test_result: "success",
                on_host_test_result: "success",
                web_tests_result: "success",
                e2e_test_result: "success",
                yts_test_result: "success",
                test_failures: {},
                failed: false
              }' > "report_${platform}.json"
          done

      - name: Upload Mock chromium_android-arm64
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-chromium_android-arm64
          path: report_chromium_android-arm64.json

      - name: Upload Mock chromium_android-arm
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-chromium_android-arm
          path: report_chromium_android-arm.json

      - name: Upload Mock chromium_android-x86
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-chromium_android-x86
          path: report_chromium_android-x86.json

      - name: Upload Mock android-arm64
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-android-arm64
          path: report_android-arm64.json

      - name: Upload Mock android-arm
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-android-arm
          path: report_android-arm.json

      - name: Upload Mock android-x86
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-android-x86
          path: report_android-x86.json
