name: android_nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-arm64
  arm:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-arm
  x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: android-x86
