name: aosp

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  mock-aosp:
    runs-on: ubuntu-latest
    steps:
      - name: Create mock report
        run: |
          jq -n \
            --arg platform "aosp-arm" \
            '{
              platform: $platform,
              config: "devel",
              build_result: "success",
              on_device_test_result: "success",
              on_host_test_result: "success",
              web_tests_result: "success",
              e2e_test_result: "success",
              yts_test_result: "success",
              test_failures: {},
              failed: false
            }' > report_aosp-arm.json

      - name: Upload Mock aosp-arm
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-aosp-arm
          path: report_aosp-arm.json
