name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - '23.lts.1\+'
      - '22.lts.1\+'
      - '21.lts.1\+'
      - '20.lts.1\+'
      - '19.lts.1\+'
      - 'rc_11'
      - 'COBALT_9'
      - 'feature/*'

concurrency:
  group: '${{ github.workflow }}-${{ inputs.platform }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.sha }}'
  cancel-in-progress: true

jobs:
  check-bug-id:
    name: Check Bug ID
    runs-on: ubuntu-latest
    steps:
      - name: Check Bug ID Present
        # v2
        uses: gsactions/commit-message-checker@16fa2d5de096ae0d35626443bcd24f1e756cafee
        with:
          pattern: '^b\/\d+$'
          flags: 'gm'
          error: 'Commit message should include at least one bug ID on a separate line (e.g. b/12345).'
