name: evergreen_nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-x86
  x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-x64
  arm-hardfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-arm-hardfp
  arm-softfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-arm-softfp

