name: evergreen

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  mock-evergreen:
    runs-on: ubuntu-latest
    steps:
      - name: Create mock reports
        run: |
          for platform in evergreen-x64 evergreen-arm-hardfp-rdk evergreen-arm-softfp evergreen-arm64; do
            jq -n \
              --arg platform "$platform" \
              '{
                platform: $platform,
                config: "devel",
                build_result: "success",
                on_device_test_result: "success",
                on_host_test_result: "success",
                web_tests_result: "success",
                e2e_test_result: "success",
                yts_test_result: "success",
                test_failures: {},
                failed: false
              }' > "report_${platform}.json"
          done

      - name: Upload Mock evergreen-x64
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-evergreen-x64
          path: report_evergreen-x64.json

      - name: Upload Mock evergreen-arm-hardfp-rdk
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-evergreen-arm-hardfp-rdk
          path: report_evergreen-arm-hardfp-rdk.json

      - name: Upload Mock evergreen-arm-softfp
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-evergreen-arm-softfp
          path: report_evergreen-arm-softfp.json

      - name: Upload Mock evergreen-arm64
        uses: actions/upload-artifact@v4
        with:
          name: validation-report-evergreen-arm64
          path: report_evergreen-arm64.json
