name: evergreen

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, labeled]
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

env:
  RUN_ODT_TESTS_ON_NIGHTLY: ${{ vars.RUN_ODT_TESTS_ON_NIGHTLY }}
  RUN_ODT_TESTS_ON_POSTSUBMIT: ${{ vars.RUN_ODT_TESTS_ON_POSTSUBMIT }}

jobs:
  varshow:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "${{ vars.RUN_ODT_TESTS_ON_NIGHTLY }}"
          echo "${{ vars.RUN_ODT_TESTS_ON_NIGHTLY }}"
          echo "${{ env.RUN_ODT_TESTS_ON_POSTSUBMIT }}"
          echo "${{ env.RUN_ODT_TESTS_ON_POSTSUBMIT }}"
  evergreen-x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-x64
      nightly: ${{ github.event.inputs.nightly }}
  evergreen-arm-hardfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-hardfp
      nightly: ${{ github.event.inputs.nightly }}
  evergreen-arm-softfp:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-arm-softfp
      nightly: ${{ github.event.inputs.nightly }}
  evergreen-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: evergreen-x86
      nightly: ${{ github.event.inputs.nightly }}
