name: evergreen-arm-softfp_nightly_23.lts.1+

on:
  workflow_dispatch:

jobs:
  CI:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-arm-softfp

