name: evergreen-x86_23.lts.1+

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:

  push:
    branches:
      - '23.lts.1\+'
  workflow_dispatch:

jobs:
  CI:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: evergreen-x86

