name: lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }}-${{ inputs.platform }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.sha }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Pip Packages
        run: pip install -r ${GITHUB_WORKSPACE}/requirements.txt
      - name: Download Resources
        run: python ${GITHUB_WORKSPACE}/download_resources.py
      - name: Download GN via CIPD
        env:
          GN_SHA256SUM: 'af7b2dcb3905bca56655e12131b365f1cba8e159db80d2022330c4f522fab2ef  /tmp/gn.zip'
          GN_HASH: r3styzkFvKVmVeEhMbNl8cuo4VnbgNICIzDE9SL6su8C
        run: |
          set -x
          set +e
          curl --location --silent --output /tmp/gn.zip "https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/${GN_HASH}"
          echo ${GN_SHA256SUM} | sha256sum --check
          unzip /tmp/gn.zip -d /usr/local/bin
          rm /tmp/gn.zip
      - name: pre-commit
        uses: ./.github/actions/pre_commit
        with:
          base_ref: ${{ github.event.pull_request.base.sha && github.event.pull_request.base.sha || github.event.base_ref }}
