name: linux

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*
  schedule:
    # GMT timezone.
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  linux-x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: linux
      nightly: ${{ github.event.inputs.nightly }}
    secrets: inherit
  linux-clang-3-9:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: linux-clang-3-9
      nightly: ${{ github.event.inputs.nightly }}
      modular: true
    secrets: inherit
  linux-gcc-6-3:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: linux-gcc-6-3
      nightly: ${{ github.event.inputs.nightly }}
      modular: true
    secrets: inherit
  # TODO(b/285632780): Enable blackbox tests for modular linux workflows.
  linux-modular:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: linux-modular
      nightly: ${{ github.event.inputs.nightly }}
      modular: true
    secrets: inherit
