name: linux_20.lts.1+

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize, labeled]
    branches:
      - '20.lts.1\+'
  push:
    branches:
      - '20.lts.1\+'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  linux:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: linux
      nightly: ${{ github.event.inputs.nightly }}
