name: linux_nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: linux
  clang-3-9:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: linux-clang-3-9
  gcc-6-3:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: linux-gcc-6-3
