name: linux_nightly_23.lts.1+

on:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  x64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: linux
