name: mac

on:
  pull_request:
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*

jobs:
  test_mac:
    permissions:
      actions: write
    runs-on: macos-latest
    steps:
      - name: Dump worker info
        run: |
          uname -a
          g++ --version
          echo "PATH=${PATH}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"
        shell: bash
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "${JOB_CONTEXT}"
        shell: bash
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "${STEPS_CONTEXT}"
        shell: bash
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "${RUNNER_CONTEXT}"
        shell: bash
      - name: Default environment variables
        run: |
          echo "The job_id is: ${GITHUB_JOB}"
          echo "The id of this action is: ${GITHUB_ACTION}"
          echo "The run id is: ${GITHUB_RUN_ID}"
          echo "The GitHub Actor's username is: ${GITHUB_ACTOR}"
          echo "GitHub SHA: ${GITHUB_SHA}"
        shell: bash
      - name: Rate limit info
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /rate_limit
        shell: bash
  chromium_mac-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: chromium_mac-arm64
      run_in_docker: false
      nightly: ${{ github.event.inputs.nightly }}
    secrets:
      datadog_api_key: ${{ secrets.DD_API_KEY }}
