name: nightly_trigger_23.lts.1+

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  trigger:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: 23.lts.1+
      - name: Trigger Nightly
        run: |
          set -x
          gh workflow run android_nightly_23.lts.1+ --ref 23.lts.1+
          gh workflow run evergreen_nightly_23.lts.1+ --ref 23.lts.1+
          gh workflow run linux_nightly_23.lts.1+ --ref 23.lts.1+
          gh workflow run raspi-2_nightly_23.lts.1+ --ref 23.lts.1+
          gh workflow run win32_nightly_23.lts.1+ --ref 23.lts.1+
        env:
          GITHUB_TOKEN: ${{ secrets.NIGHTLY_TRIGGER_PAT }}
