name: PR badges

on:
  pull_request_target:
    branches:
      - 'main'
      - '23.lts.1\+'
      - '22.lts.1\+'
      - '21.lts.1\+'
      - '20.lts.1\+'
      - '19.lts.1\+'
      - 'rc_11'
      - 'COBALT_9'

concurrency:
  group: '${{ github.workflow }}-${{ inputs.platform }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.sha }}'
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // Get the existing comments.
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
            })

            // Find any comment already made by the bot.
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Build Status')
            })
            const workflows = ["lint", "android", "evergreen", "linux", "raspi-2", "stub", "win32"]
            var commentBody = `
            ## Build Status
            | Workflow  | Status                                                                                                                                                                                                                                               |
            | --------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
            `
            for (let i = 0; i < workflows.length; i++) {
              commentBody += "| " + workflows[i] + "      | [![" + workflows[i] +"](${{github.server_url}}/${{github.repository}}/actions/workflows/" + workflows[i] + ".yaml/badge.svg?branch=${{ github.head_ref }})](${{github.server_url}}/${{github.repository}}/actions/workflows/" + workflows[i] + ".yaml?query=branch%3A${{ github.head_ref }})                |\n"
            }
            if (botComment) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
              })
            }
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              body: commentBody
            })
