name: raspi-2_22.lts.1+

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - '22.lts.1\+'
  push:
    branches:
      - '22.lts.1\+'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  raspi-2:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: raspi-2

