name: stub

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  stub:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: stub
      nightly: 'false'
