name: repo_vars

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RUN_ODT_TESTS_ON_NIGHTLY: ${{ vars.RUN_ODT_TESTS_ON_NIGHTLY }}
  RUN_ODT_TESTS_ON_POSTSUBMIT: ${{ vars.RUN_ODT_TESTS_ON_POSTSUBMIT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "${{ vars.RUN_ODT_TESTS_ON_NIGHTLY }}"
          echo "${{ vars.RUN_ODT_TESTS_ON_POSTSUBMIT }}"
          echo "${{ env.RUN_ODT_TESTS_ON_NIGHTLY }}"
          echo "${{ env.RUN_ODT_TESTS_ON_POSTSUBMIT }}"
