name: 'Test Report'
on:
  workflow_run:
    # runs after main workflow
    workflows:
      - evergreen
      - linux
      # TODO
      # - win32
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Create Report
        uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
        with:
          name: Cobalt Unit Tests
          artifact: test-results
          path: '**/*.xml'
          reporter: jest-junit
