name: tvos

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - main
      - experimental/*
      - feature/*
      - 'stack/**'
  push:
    branches:
      - main
      - experimental/*
      - feature/*
      - 'stack/**'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

permissions: read-all

jobs:
  tvos-arm64-simulator:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: tvos-arm64-simulator
      nightly: ${{ github.event.inputs.nightly }}
