name: Upload Unit Test Reports

on:
  workflow_run:
    workflows:
      - linux
      # TODO: xml file generation on windows
      # - win32
      # TODO: Other platforms
    types:
      - completed

jobs:
  # Gets unit test report from artifact storage and uploads them to DataDog.
    unit-test-report:
      permissions: {}
      if: always()
      runs-on: ubuntu-latest
      name: Upload Unit Test Reports
      env:
        DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
        DATADOG_SITE: us5.datadoghq.com
      steps:
        # TODO: Check if artifact exists, or
        # TODO: Always upload a report, empty -> no upload
        - name: Collect Unit Test Reports
          uses: actions/download-artifact@v3
          with:
            name: unit-test-reports
            path: unit-test-reports/
        - name: Install node
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Get Datadog CLI
          shell: bash
          # TODO: pin version (with checksum?)
          run: npm install -g @datadog/datadog-ci
        - name: Upload the JUnit files
          shell: bash
          run: |
            # Loop over platform folders in archive
            for dir in unit-test-reports/*/; do
              echo "Uploading $dir test report"

              service="${{ github.event.repository.name }}"
              tags=`cat ${dir}TAGS`

              datadog-ci junit upload \
                        --service $service \
                        --env ci \
                        --tags $tags \
                        $dir
            done
