name: win32_23.lts.1+

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, labeled]
    branches:
      - '23.lts.1\+'
  push:
    branches:
      - '23.lts.1\+'
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

concurrency:
  group: '${{ github.workflow }}-${{ github.event_name }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  win:
    uses: ./.github/workflows/main_win.yaml
    permissions:
      packages: write
    with:
      platform: win32
      nightly: ${{ github.event.inputs.nightly }}
