name: win32_nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  CI:
    uses: ./.github/workflows/main_win.yaml
    permissions:
      packages: write
    with:
      platform: win32

