name: win32_nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  win32:
    uses: ./.github/workflows/main_win.yaml
    permissions:
      packages: write
    with:
      platform: win32

