name: win32_23.lts.1+

on:
  pull_request:
    types: [opened, reopened, edited, synchronize, labeled]
    branches:
      - '23.lts.1\+'
  push:
    branches:
      - '23.lts.1\+'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  win:
    uses: ./.github/workflows/main_win.yaml
    permissions:
      packages: write
    with:
      platform: win32
