name: workflow_trigger

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Branch
        options:
          - '23.lts.1\+'
          - '22.lts.1\+'
          - '21.lts.1\+'
          - '20.lts.1\+'
          - '19.lts.1\+'
          - 'rc_11'
          - 'COBALT_9'
      workflow:
        type: choice
        description: Workflow name
        options:
          - 'android'
          - 'evergreen'
          - 'linux'
          - 'raspi'
          - 'win32'
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  trigger:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{github.event.branch}}
      - name: Trigger Nightly
        run: |
          set -x
          gh workflow run ${{github.event.workflow}}_${{github.event.branch}} --ref ${{github.event.branch}} -f nightly=${{github.event.nightly}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
