name: Workflow Debug

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main
      - experimental/*
      - feature/*
  push:
    branches:
      - main
      - experimental/*
      - feature/*
  schedule:
    # GMT timezone.
    - cron: '0 9 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

permissions: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Print github context
        shell: bash
        run: |
          echo '${{ toJSON(github) }}' | jq '.'
